# Site settings
title: Luiz Cezer - Ruby on Rails Developer
email: lccezinha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meus rascunhos de programação.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lccezinha
github_username:  lccezinha

# Build settings
markdown: kramdown
