# Site settings
title: Luiz Cezer - Ruby on Rails Developer
email: lccezinha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Movido a Coca-Cola & Thrash Metal /m/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lccezinha.github.io"
twitter_username: lccezinha
github_username:  lccezinha
linkedin_username: luizcezer

# Build settings
markdown: kramdown

analytics :
  provider : google
  google :
      tracking_id : 'UA-37959294-2'

disqus_shortname: lccezinha
